name: Publish documentation to public

on: [workflow_dispatch]
jobs:
  install-publish:
    name: Upload docs to production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy a all doc to s3
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          source: 'docs/*'
          dest: 's3://${{ secret.PROD_AWS_DOCUMENTATION_BUCKET }}/docs/general/'
          flags: --recursive

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secret.PROD_AWS_DOCUMENTATION_DISTRIBUTION }}
          PATHS: "/docs/general"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
